export const rawDefaultContent = {
  version: 1,
  simulation: {
    tickMs: 50,
    dayDurationMs: 75_000,
    nightDurationMs: 75_000,
    finalDurationMs: 90_000,
  },
  world: {
    width: 2_200,
    height: 2_200,
    resourceNodeCount: 4,
    woodPerNode: 10,
    woodCollectedPerInteraction: 4,
    initialSleeperCount: 9,
    playerStartOffsetY: 120,
    resourceRingStartRadius: 440,
    resourceRingStepRadius: 140,
    resourceAngleJitterRadians: 0.3,
    guardianOffset: 58,
    initialSleeperRing: {
      minimumRadius: 420,
      maximumRadius: 960,
    },
    debugEnemySpawnRing: {
      minimumRadius: 650,
      maximumRadius: 900,
    },
  },
  player: {
    maxHp: 85,
    moveSpeed: 240,
    carryCapacity: 8,
    interactionRange: 86,
  },
  sword: {
    autoDamage: 9,
    autoRange: 105,
    autoCooldownMs: 750,
    lungeDamage: 22,
    lungeDistance: 150,
    lungeRadius: 72,
    lungeCooldownMs: 6_000,
    lungeWakeRadius: 150,
    automaticAttackWakeRadius: 140,
  },
  barrier: {
    maxWard: 12,
    wardRefreshMs: 10_000,
    activeRadius: 175,
    activeDurationMs: 3_000,
    activeCooldownMs: 14_000,
    damageReduction: 0.65,
  },
  village: {
    maxHp: 320,
    areaRadius: 230,
    dayRegenPerSecond: 2,
    underAttackRegenMultiplier: 0.25,
    levelTwoCost: 8,
    ultimateCost: 12,
    ultimateMinimumPlayerLevel: 2,
  },
  defense: {
    buildCost: 6,
    buildDurationMs: 5_000,
    minimumHeartDistance: 78,
    minimumSpacing: 82,
    maxHp: 130,
    damage: 11,
    range: 320,
    cooldownMs: 900,
    repairCost: 1,
    repairAmount: 45,
    placementOuterMargin: 28,
  },
  progression: {
    experiencePerLevel: [15, 30, 50],
    fallbackExperienceToNext: 999,
    upgradeChoiceCount: 3,
  },
  enemies: {
    guardian: {
      maxHp: 50,
      damage: 10,
      speed: 78,
      attackRange: 38,
      attackCooldownMs: 1_050,
      experience: 12,
      woodReward: 0,
    },
    sleeper: {
      maxHp: 38,
      damage: 7,
      speed: 72,
      attackRange: 36,
      attackCooldownMs: 1_100,
      experience: 8,
      woodReward: 0,
    },
    raider: {
      maxHp: 46,
      damage: 9,
      speed: 86,
      attackRange: 38,
      attackCooldownMs: 1_000,
      experience: 9,
      woodReward: 1,
    },
    brute: {
      maxHp: 130,
      damage: 16,
      speed: 52,
      attackRange: 48,
      attackCooldownMs: 1_350,
      experience: 22,
      woodReward: 2,
    },
  },
  enemyBehavior: {
    collisionRadius: 18,
    guardianAggroRange: 165,
    guardianChaseRange: 320,
    guardianReturnTolerance: 4,
    dayAggroRange: 145,
    dayChaseRange: 340,
    dayReturnTolerance: 6,
    assaultPlayerPriorityRange: 115,
    assaultDefenseDetectionRange: 205,
    defenseContactPadding: 24,
    villageContactPadding: 48,
  },
  waves: {
    night: {
      baseRaiderCount: 3,
      raidersPerCycle: 2,
      bruteStartCycle: 2,
      bruteBaseCount: 1,
      brutesPerCycle: 1,
      spawnRing: {
        minimumRadius: 850,
        maximumRadius: 1_020,
      },
    },
    escalation: {
      hpPerCycle: 0.12,
      damagePerCycle: 0.08,
    },
    dayReinforcements: {
      baseCount: 2,
      countPerCycle: 2,
      maximumCount: 7,
      spawnRing: {
        minimumRadius: 620,
        maximumRadius: 980,
      },
    },
    final: {
      raiderCount: 14,
      raiderSpawnRing: {
        minimumRadius: 860,
        maximumRadius: 1_020,
      },
      bruteCount: 4,
      bruteSpawnRing: {
        minimumRadius: 900,
        maximumRadius: 1_040,
      },
    },
  },
  upgrades: [
    {
      id: 'sword-sharp-edge',
      name: 'Tranchant affûté',
      description: '+35 % de dégâts pour Taillade.',
      discipline: 'sword',
      effect: 'sword-damage',
      value: 1.35,
      weight: 1,
    },
    {
      id: 'barrier-reinforced-ward',
      name: 'Égide renforcée',
      description: '+15 points de garde maximale.',
      discipline: 'barrier',
      effect: 'ward-capacity',
      value: 15,
      weight: 1,
    },
    {
      id: 'sword-quick-hands',
      name: 'Gestes vifs',
      description: 'Taillade se déclenche 20 % plus vite.',
      discipline: 'sword',
      effect: 'sword-speed',
      value: 0.8,
      weight: 1,
    },
    {
      id: 'barrier-lasting-dome',
      name: 'Dôme persistant',
      description: '+1,5 seconde de durée pour Barrière.',
      discipline: 'barrier',
      effect: 'barrier-duration',
      value: 1_500,
      weight: 1,
    },
    {
      id: 'sword-long-reach',
      name: 'Allonge',
      description: '+30 unités de portée pour Taillade.',
      discipline: 'sword',
      effect: 'sword-range',
      value: 30,
      weight: 1,
    },
    {
      id: 'sword-relentless-lunge',
      name: 'Fente implacable',
      description: 'Fente récupère 25 % plus vite.',
      discipline: 'sword',
      effect: 'lunge-cooldown',
      value: 0.75,
      weight: 1,
    },
  ],
} as const;
